### ISSUE TITLE
Use yaml config file for Galaxy helm variables

### ISSUE THREAD

**Issue by sneumann** [phnmnl/KubeNow-plugin#17]
Hi, currently the helm variables are passed to the Galaxy chart by ansible through the command line in 
https://github.com/phnmnl/KubeNow-plugin/blob/master/playbooks/roles/galaxy/tasks/main.yml#L13

It would be great to keep them in a config file, as @pcm32 does for our public instances, 
so that they can be installed through a shorter `helm install -f galaxyconfig.yaml --version 1.5.4 galaxy-helm-repo/galaxy-stable`
as described on https://github.com/phnmnl/phenomenal-h2020/wiki/Galaxy-Release-Procedure#updating-a-running-galaxy-instance. Yours, Steffen

**Comment by pcm32** [comment]
This would be very good, as it would ease the pain when moving to the new Galaxy chart scheme here, which should be doable now that I have fixed ingresses access.

**Comment by andersla** [comment]
Great suggestion. I guess I will fix this similar to how the Dashboard playbook is applied: https://github.com/phnmnl/KubeNow-plugin/blob/master/playbooks/roles/kubernetes-dashboard/tasks/main.yml

**Comment by andersla** [comment]
Will be fixed via #19

**Comment by sneumann** [comment]
#19 has been merged, variables are now in `plugins/phnmnl/KubeNow-plugin/playbooks/roles/galaxy/templates/galaxy-helm-values.yaml.j2` in the kubenow directory for an installation. I guess this can be closed then. Yours, Steffen
